# Generated by Django 4.1.3 on 2023-07-03 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profile_age_remove_profile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=100)),
                ('Video_name', models.CharField(max_length=100)),
                ('main_img', models.ImageField(upload_to='post_videos')),
                ('details', models.TextField()),
                ('no_of_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=100)),
                ('Video_name', models.CharField(max_length=100)),
                ('main_img', models.FileField(upload_to='post_videos')),
                ('details', models.TextField()),
                ('no_of_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='main_img1',
            field=models.FileField(default='blank-img.png', upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_img2',
            field=models.FileField(default='blank-img.png', upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_img3',
            field=models.FileField(default='blank-img.png', upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_img4',
            field=models.FileField(default='blank-img.png', upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_img5',
            field=models.FileField(default='blank-img.png', upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_img6',
            field=models.FileField(default='blank-img.png', upload_to='post_videos'),
        ),
    ]
