# Generated by Django 4.1.3 on 2023-07-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='texts',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='video',
            new_name='videos',
        ),
    ]
